### ISSUE TITLE
Validate peripheral on init

### ISSUE THREAD

**Issue by danielspofford** [nerves-time/nerves_time_rtc_ds3231#6]
Reference: https://github.com/nerves-time/nerves_time_rtc_ds3231/pull/3#issuecomment-597418359

The removal of the check (as implemented, not conceptually) was because how it was going about checking was not good. See PR.

--

The only comms you can have with the DS3231 is reading and writing registers. None of the registers contain a static/reliable/identifiable value to check. I think our options would be one of:

- General read success. An I2C read against bus and address with a read length of all registers.
- Observe counting seconds. Read seconds into `initial` and wait `expected` seconds and re-read again into `actual`. If `abs(expected - (actual - initial)) <= epsilon ` then “it looks like it is keeping time”.

Neither of these will guarantee the DS3231 is actually what you are talking to.

**Comment by fhunleth** [comment]
Option 1 (general read success) is sufficient and there's no need to read all registers. One register is sufficient. Ideally the part would have an ID register, but since it doesn't, it's good enough to check that the I2C address responds. The purpose here isn't perfection - it's to detect misconfiguration and broken hardware early on.

**Comment by jsimmonds2** [comment]
> Neither of these will guarantee the DS3231 is actually what you are talking to.

Well said :-)  As we know, this part is a "classic" :: no **ID**, no **Config**, etc., etc 🙂
